### ISSUE TITLE
Choose a submersible pump 

### ISSUE THREAD

**Issue by josepmaria-carbonell** [Integrated-Project-2-UVic-UCC/covid-device#10]
It is not possible to buy the submersible pump  in the link supplied.
Please check if one of the alternatives are suitable for you.

1. https://www.amazon.es/Bomba-sumergible-escobillas-alimentario-paquete/dp/B07TF9HR4W
2. https://www.amazon.es/mountain-ark-Sumergible-hidrop%C3%B3nicas-elevaci%C3%B3n/dp/B07N1K1GYM

We will expect your decision before ordering it.

@Integrated-Project-2-UVic-UCC/covid-device

**Comment by Alex-Howroyd** [comment]
We choose this alternative because the specifications are similars than the original. 
https://www.amazon.es/mountain-ark-Sumergible-hidrop%C3%B3nicas-elevaci%C3%B3n/dp/B07N1K1GYM
Thankyou.

**Comment by ghost** [comment]
> We choose this alternative because the specifications are similars than the original. 
> https://www.amazon.es/mountain-ark-Sumergible-hidrop%C3%B3nicas-elevaci%C3%B3n/dp/B07N1K1GYM
> Thankyou.


So now also we are going to need tube or not?

**Comment by josepmaria-carbonell** [comment]
I suggest to make a review and try to find more options if you need more components. The price of the second option is more than twice the price of the one you had in the shopping list. Jordi gave me those alternatives but we/you can look for other options.

**Comment by Alex-Howroyd** [comment]
Yes Maza we will need the tubs but we will have to buy it in another place I think. All I found are mini pumps submersible without the tubs.

In this shortly time, this are the best options I have found:

https://www.amazon.es/dp/B07WZMYXYW/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B07WZMYXYW&pd_rd_w=uYmpd&pf_rd_p=c4c9c78d-928d-4cf2-ba41-9873ab24035f&pd_rd_wg=fdUDX&pf_rd_r=5GA3SJZZF02W1B5T6SY6&pd_rd_r=dd117184-db5c-44a4-8e13-0bba13f27603&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzVExDU0s5RDk4QVpLJmVuY3J5cHRlZElkPUEwMzU4ODU4MVM0UEVPMktQUDI4JmVuY3J5cHRlZEFkSWQ9QTA0MzExMzczOFlVQ1NBU0dISVNaJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

https://www.amazon.es/dp/B07WZLSZ49/ref=sspa_dk_detail_0?psc=1&pd_rd_i=B07WZLSZ49&pd_rd_w=1A6Sa&pf_rd_p=c4c9c78d-928d-4cf2-ba41-9873ab24035f&pd_rd_wg=6Dnpx&pf_rd_r=599W7XGZBHQ37T6A7PM9&pd_rd_r=1e4914ec-5b8c-43e3-bfa6-ac47fc430d7b&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzQ0Q2VzZZWUpKTjhEJmVuY3J5cHRlZElkPUEwODYxMDUwM1U1RlZIT040NUFQNyZlbmNyeXB0ZWRBZElkPUEwMzEzOTQwMlE4Mk1PQ1lJU08xRSZ3aWRnZXROYW1lPXNwX2RldGFpbCZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

https://www.amazon.es/dp/B07J6NF2KQ/ref=sspa_dk_detail_0?pd_rd_i=B07J6NF2KQ&pd_rd_w=wV9tY&pf_rd_p=c4c9c78d-928d-4cf2-ba41-9873ab24035f&pd_rd_wg=kQOYI&pf_rd_r=C287HNKVQE2420WRRNS5&pd_rd_r=d87d18ba-7b61-49e0-8859-c45f05854f1a&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzNDExSzExSVdGM0REJmVuY3J5cHRlZElkPUEwODQ3OTA0VEVRMjBRRTJGV0ZMJmVuY3J5cHRlZEFkSWQ9QTAwMzA2ODExNTJJVEpFRUdCSlNSJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1

**Comment by josepmaria-carbonell** [comment]
This is the last proposal, just confirm if that is ok:

https://www.amazon.es/RUNCCI-YUN-Sumergible-Cepillo-paraTanque-Vertical/dp/B08BZBN29C

@Integrated-Project-2-UVic-UCC/covid-device
