### ISSUE TITLE
Webpage 

### ISSUE THREAD

**Issue by RamonnMompart** [Integrated-Project-2-UVic-UCC/covid-device#12]
Design and creation of the website from which customers can see the product.
 Subsections:

- [x] Contact
- [x] About us
- [ ] Blog
- [x] Start
- [ ] Service

**Comment by josepmaria-carbonell** [comment]
You can add the link of the webpage here

**Comment by oriol-vall** [comment]
Sorry we think we have already in the issue. 

That's it's our link: 
https://ramonmx14.wixsite.com/my-site-1
