### ISSUE TITLE
Building structure

### ISSUE THREAD

**Issue by Alex-Howroyd** [Integrated-Project-2-UVic-UCC/covid-device#7]

**Comment by oriol-vall** [comment]
**To create our structure of the project**
![image](https://user-images.githubusercontent.com/79116444/114719319-3dc4c580-9d37-11eb-83f9-52a984e93494.png) ![image](https://user-images.githubusercontent.com/79116444/114719652-97c58b00-9d37-11eb-857d-b8684069f466.png)
![image](https://user-images.githubusercontent.com/79116444/114721732-7fef0680-9d39-11eb-9a07-b0d66f5e03f1.png)

**Comment by oriol-vall** [comment]
To progress about the structure of the project we will change the dimensions: 
Height: 1600 mm ---->  1450mm 
Depth: 500mm -----> 280 mm
